export const StackNav = {
  Login: "Login",
  Signup: "Signup",
  ForgotPassword: "ForgotPassword",
  Home: "Home",
  Start: "Start",
  Age: "Age",
  FirstName: "FirstName",
  LastName: "LastName",
  Gender: "Gender",
  Grade: "Grade",
  LocationPermission: "LocationPermission",
  School: "School",
  Phone: "Phone",
  ContactsPermission: "ContactsPermission",
  Friends: "Friends",
  Password: "Password",
  WaitingRoom: "WaitingRoom",
  MyCaps: "MyCaps",
  WhatTheySay: "WhatTheySay",
  Subscription: "Subscription",
  ReplyTo: "ReplyTo",
  Profile: "Profile",
};
