export const Images = {
  logo: require("../assets/logo.png"),
  buttonBack: require("../assets/buttonBack.png"),
  genderBtnBack: require("../assets/genderBtnBack.png"),
  school1: require("../assets/images/school1.png"),
  school2: require("../assets/images/school2.png"),
  school3: require("../assets/images/school3.png"),
  school4: require("../assets/images/school4.png"),
  school5: require("../assets/images/school5.png"),
  school6: require("../assets/images/school6.png"),
  school7: require("../assets/images/school7.png"),
  school8: require("../assets/images/school8.png"),
  school9: require("../assets/images/school9.png"),
  boy: require("../assets/images/boy.png"),
  girl: require("../assets/images/girl.png"),
  nonBinary: require("../assets/images/non-binary.png"),
  success: require("../assets/images/success.gif"),
};
